# Generated by Django 5.0.1 on 2024-01-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_productos_proveedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='numero_producto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
